import videoDummy from "../../../../assets/admin/Content/videoDummy.png";
import businessImage from "../../../../assets/admin/Profile/profilePicture.png";
export const contentApprovalDummyData = [
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
  {
    checked:false,
    image: videoDummy,
    title: "Blueberry Pancakes",
    tags: ["Carbs", "Breakfast", "Fruit", "Granola", "Food"],
    businessImage: businessImage,
    businessName:"Food Hallen",
    type: "Business",
    category: "SneakPiq",
    added: "Sep 25, 2022",
    views: "22.3K",
    shares: "22.3K",
    saves: "9.5K",
    impressions: "505K",
    comments:
      "Dmmy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard",
    status: "Review",
  },
];
